"""add protein

Revision ID: a182293343ff
Revises: 53d1661a19bd
Create Date: 2017-11-07 23:46:01.137373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182293343ff'
down_revision = '53d1661a19bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('random_sequence_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['random_sequence_id'], ['sequence.id'], name=op.f('fk_protein_random_sequence_id_sequence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protein'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protein')
    # ### end Alembic commands ###
