"""name remove unique

Revision ID: f2ce11a6b1ad
Revises: 71173ed527a2
Create Date: 2017-11-05 23:57:43.047228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ce11a6b1ad'
down_revision = '71173ed527a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_disorder_prediction_predictor_name', 'disorder_prediction', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_disorder_prediction_predictor_name', 'disorder_prediction', ['predictor_name'])
    # ### end Alembic commands ###
