"""raw to floatranger-cd

Revision ID: 53d1661a19bd
Revises: f2ce11a6b1ad
Create Date: 2017-11-06 11:08:18.660689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53d1661a19bd'
down_revision = 'f2ce11a6b1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disorder_prediction_raw', 'data',
               existing_type=postgresql.ARRAY(sa.SMALLINT()),
               type_=postgresql.ARRAY(sa.FLOAT()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disorder_prediction_raw', 'data',
               existing_type=sa.Float(),
               type_=postgresql.ARRAY(sa.SMALLINT()),
               existing_nullable=True)
    # ### end Alembic commands ###
