"""add regions

Revision ID: 71173ed527a2
Revises: f227700e0f82
Create Date: 2017-11-05 23:54:58.964648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71173ed527a2'
down_revision = 'f227700e0f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disorder_prediction_regions', sa.Column('end', sa.Integer(), nullable=False))
    op.add_column('disorder_prediction_regions', sa.Column('start', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disorder_prediction_regions', 'start')
    op.drop_column('disorder_prediction_regions', 'end')
    # ### end Alembic commands ###
